<a href="https://colab.research.google.com/github/alecp-23/tc1002s_st/blob/main/Actividad_1_A01739472.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

ACTIVIDAD DE NUMPY

In [ ]:
#1
import numpy as np
arr=np.array([5,5,5,5,5,5,5,5,5,5])
print(arr)
#

[5 5 5 5 5 5 5 5 5 5]


In [ ]:
#Crea un arreglo de enteros pares desde 10, inclusive, hasta 50, inclusive.
arr=np.arange(10,51,2)
print(arr)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [ ]:
#3. Crea una matriz cuadrada de 4 por 4 de números enteros aleatorios.
arr=np.random.randint(1,100,(4,4))
print(arr)

[[87 34 96 40]
 [54 87 23 78]
 [ 2 68 60  1]
 [38 13 80 33]]


In [ ]:
#4. Genera un arreglo de 10 números aleatorios entre 0 y 1 y calcula la suma de todos sus elementos.
arr=np.random.rand(10)
print(arr)
print(np.sum(arr))

[0.08710533 0.35883295 0.75610949 0.27177549 0.39499386 0.27933708
 0.2049119  0.7813877  0.61952503 0.72195139]
4.475930213254921


In [ ]:
#5. Genera un arreglo de 10 números aleatorios entre 0 y 1 y calcula su media.
arr=np.random.rand(10)
print(arr)
print(np.mean(arr))

[0.76853772 0.91730546 0.23060152 0.88830425 0.33381265 0.91761027
 0.87822206 0.2925838  0.09434834 0.28689982]
0.5608225884232549
